version: '3'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: onlymock
    restart: always
    ports: 
      - "9091:51773"
      - "9092:52773"
    volumes:
      - ./Export:/opt/mockfw/export
    
    