var whStemmer = new Snowball();
var whBaseNameList = [
/*0*/ "ch01s01.html",
/*1*/ "ch01.html",
/*2*/ "index.html"
];
var whTitleList = [
/*0*/ "1. REST mocked methods",
/*1*/ "Chapter 1. ZK.Mocks.Restaurant",
/*2*/ "Restaurant - Mock documentation"
];
// 53 words.
var whWordMap = {
"restaur": [0,2],
"none": [0],
"zk.mocks.restaur": [1],
"put": [0],
"mockfw": [0],
"quantiti": [0],
"burger": [0],
"post": [0],
"api": [0],
"id": [0],
"order": [0],
"localhost": [0],
"method": [0],
"town": [0],
"edit": [0],
"norvak": [0],
"fals": [0],
"rizoto": [0],
"exist": [0],
"delay": [0],
"phone": [0],
"name": [0],
"mock": [[0,2]],
"http": [0],
"doe": [0],
"bodi": [0],
"brno": [0],
"tabl": [0],
"chapter": [1],
"code": [0],
"document": [2],
"save": [0],
"deliv": [0],
"botanicka": [0],
"delet": [0],
"undeliveredord": [0],
"respons": [0],
"not": [0],
"street": [0],
"get": [0],
"have": [0],
"tow": [0],
"ani": [0],
"rest": [0],
"address": [0],
"irisown": [2],
"was": [0],
"meal": [0],
"alergen": [0],
"postcod": [0],
"martin": [0],
"novak": [0],
"return": [0]
};
