var whStemmer = new Snowball();
var whBaseNameList = [
/*0*/ "ch01s01.html",
/*1*/ "ch01s02.html",
/*2*/ "ch01.html",
/*3*/ "index.html"
];
var whTitleList = [
/*0*/ "1. Local mocked methods",
/*1*/ "2. REST mocked methods",
/*2*/ "Chapter 1. MockFW.Mocks.Restaurant",
/*3*/ "Restaurant - Mock documentation"
];
// 55 words.
var whWordMap = {
"restaur": [1,3],
"none": [1,0],
"put": [1],
"mockfw": [1],
"quantiti": [1],
"burger": [1],
"post": [1],
"id": [1,0],
"api": [1],
"order": [1,0],
"localhost": [1],
"method": [1,0],
"town": [1],
"edit": [1],
"norvak": [1],
"fals": [1],
"rizoto": [1],
"exist": [1],
"delay": [1],
"phone": [1],
"name": [1],
"mock": [[0,1,3]],
"http": [1],
"doe": [1],
"bodi": [1],
"brno": [1],
"tabl": [1,0],
"chapter": [2],
"code": [1],
"document": [3],
"paramet": [0],
"save": [1],
"deliv": [1],
"botanicka": [1],
"delet": [1],
"undeliveredord": [1],
"respons": [1,0],
"local": [0],
"not": [1],
"street": [1],
"get": [1],
"have": [1],
"tow": [1],
"ani": [1],
"rest": [1],
"address": [1],
"irisown": [3],
"was": [1],
"mockfw.mocks.restaur": [2],
"meal": [1],
"alergen": [1],
"postcod": [1],
"martin": [1],
"novak": [1],
"return": [1]
};
